name: Repo and Flutter configuration
description: Checkout repository and setup Java & Flutter

inputs:
  flutter_version:
    description: "Versi칩n de Flutter que se instalar치 en el runner"
    default: 3.38.3

  flutter_channel:
    description: "Canal de Flutter a utilizar (stable, beta, dev)"
    default: stable

  java_version:
    description: "Versi칩n de Java requerida para compilar el proyecto Android"
    default: "17"

  java_distribution:
    description: "Distribuci칩n de Java a usar (temurin, zulu, adopt, etc.)"
    default: temurin

runs:
  using: composite
  steps:
    - name: Clonando repositorio
      uses: actions/checkout@v4

    - name: Configurando Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}

    - name: Configurando Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: ${{ inputs.flutter_channel }}
        cache: true
